network:
        version: 2
        renderer: networkd
        #wifis:
        #        wlan0:
        #                dhcp4: yes
        #                dhcp4-overrides:
        #                        route-metric: 50
        #                access-points:
        #                        "cosofteck_test":
        #                                password: "12345678"
        ethernets:
                eth0:
                        addresses:
                                - 192.168.1.100/24
                        routes:
                                - to: 0.0.0.0/0
                                  via: 192.168.1.1
                                  metric: 100

                eth1:
                        dhcp4: yes
                        dhcp4-overrides:
                                route-metric: 80
                eth2:
                        dhcp4: yes
                        dhcp4-overrides:
                                route-metric: 10


